force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Verified</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Decline to Say</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MemberPlan__c.field-meta.xml
<CustomField>
    <fullName>MemberPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Plan</label>
    <referenceTo>MemberPlan__c</referenceTo>
    <relationshipLabel>Plan Members</relationshipLabel>
    <relationshipName>MemberPlan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/NPI__c.field-meta.xml
<CustomField>
    <fullName>NPI__c</fullName>
    <label>National Provider Identifier (NPI)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeName__c</field>
            <operation>equals</operation>
            <value>Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ProviderSuffix__c.field-meta.xml
<CustomField>
    <fullName>ProviderSuffix__c</fullName>
    <label>Provider Suffix</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AE-C</fullName>
            </value>
            <value>
                <fullName>ANP</fullName>
            </value>
            <value>
                <fullName>ATC</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AuD</fullName>
            </value>
            <value>
                <fullName>CCC-A</fullName>
            </value>
            <value>
                <fullName>CCC-SLP</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>CCM</fullName>
            </value>
            <value>
                <fullName>CCRN</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CDA</fullName>
            </value>
            <value>
                <fullName>CDE</fullName>
            </value>
            <value>
                <fullName>CDTC</fullName>
            </value>
            <value>
                <fullName>CEN</fullName>
            </value>
            <value>
                <fullName>CFNP</fullName>
            </value>
            <value>
                <fullName>CGC</fullName>
            </value>
            <value>
                <fullName>ChD</fullName>
            </value>
            <value>
                <fullName>DCh</fullName>
            </value>
            <value>
                <fullName>CHN</fullName>
            </value>
            <value>
                <fullName>CHT</fullName>
            </value>
            <value>
                <fullName>CLE</fullName>
            </value>
            <value>
                <fullName>CLT</fullName>
            </value>
            <value>
                <fullName>CMA</fullName>
            </value>
            <value>
                <fullName>CNA</fullName>
            </value>
            <value>
                <fullName>CNM</fullName>
            </value>
            <value>
                <fullName>CNP</fullName>
            </value>
            <value>
                <fullName>CNS</fullName>
            </value>
            <value>
                <fullName>CNSC</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Patient.recordType-meta.xml
<RecordType>
    <fullName>Patient</fullName>
    <active>true</active>
    <description>Patient Details</description>
    <label>Patient</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <description>Provider Information</description>
    <label>Provider</label>
</RecordType>

force-app/main/default/objects/CareBenefitVerification__c/CareBenefitVerification__c.object-meta.xml
<CustomObject>
    <label>Care Benefit Verification</label>
    <nameField>
        <displayFormat>CBV-{0000000}</displayFormat>
        <label>CareBenefitVerification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Benefit Verifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CareBenefitVerification__c/fields/CareBenefitVerificationRequest__c.field-meta.xml
<CustomField>
    <fullName>CareBenefitVerificationRequest__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Care Benefit Verification Request</label>
    <referenceTo>CareBenefitVerifyRequest__c</referenceTo>
    <relationshipLabel>Care Benefit Verifications Requests</relationshipLabel>
    <relationshipName>Care_Benefit_Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/CareBenefitVerifyRequest__c.object-meta.xml
<CustomObject>
    <label>Care Benefit Verification Request</label>
    <nameField>
        <displayFormat>CBVR-{0000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Benefit Verification Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <label>Date Of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/DiagnosisCode__c.field-meta.xml
<CustomField>
    <fullName>DiagnosisCode__c</fullName>
    <label>Diagnosis Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Prefer Not To Say</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/GroupNumber__c.field-meta.xml
<CustomField>
    <fullName>GroupNumber__c</fullName>
    <label>Group Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/NPI__c.field-meta.xml
<CustomField>
    <fullName>NPI__c</fullName>
    <label>NPI</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>Policy Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/ProcedureCode__c.field-meta.xml
<CustomField>
    <fullName>ProcedureCode__c</fullName>
    <label>Procedure Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/ServiceDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceDate__c</fullName>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/StatusReason__c.field-meta.xml
<CustomField>
    <fullName>StatusReason__c</fullName>
    <label>StatusReason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/SubscriberId__c.field-meta.xml
<CustomField>
    <fullName>SubscriberId__c</fullName>
    <label>Subscriber ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MemberPlan__c/MemberPlan__c.object-meta.xml
<CustomObject>
    <label>Member Plan</label>
    <nameField>
        <label>Insurance Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MemberPlan__c/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>Policy Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MemberPlan__c/fields/SubscriberId__c.field-meta.xml
<CustomField>
    <fullName>SubscriberId__c</fullName>
    <label>Subscriber Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceDetail__c/ServiceDetail__c.object-meta.xml
<CustomObject>
    <label>Service Detail</label>
    <nameField>
        <displayFormat>SD-{000000}</displayFormat>
        <label>Service Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDetail__c/fields/DiagnosisCode__c.field-meta.xml
<CustomField>
    <fullName>DiagnosisCode__c</fullName>
    <label>Diagnosis Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceDetail__c/fields/MasterDetailToAccount__c.field-meta.xml
<CustomField>
    <fullName>MasterDetailToAccount__c</fullName>
    <label>MasterDetailToAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Service Details</relationshipLabel>
    <relationshipName>Patient_ServiceDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceDetail__c/fields/ProcedureCode__c.field-meta.xml
<CustomField>
    <fullName>ProcedureCode__c</fullName>
    <label>Procedure Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceDetail__c/fields/ServiceDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Service Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceDetail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Verification Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceDetail__c/fields/StatusReason__c.field-meta.xml
<CustomField>
    <fullName>StatusReason__c</fullName>
    <label>Status Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceDetail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Service Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Infusion</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InfinitusAPIIntegrationTest.cls
@isTest
private class InfinitusAPIIntegrationTest {
    @TestSetup
    private static void dataFactory() {
        MemberPlan__c memberPlan = new MemberPlan__c(
            Name                 = 'Test Member Plan',
            SubscriberId__c      = UUID.randomUUID().toString(),
            GroupNumber__c       = UUID.randomUUID().toString(),
            PolicyNumber__c      = UUID.randomUUID().toString()
        );
        insert memberPlan;
        Account provider = new Account(
            RecordTypeId         = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId(),
            Salutation__c        = 'Dr.',
            Name                 = 'Test Provider',
            ProviderSuffix__c    = 'MD',
            Gender__c            = 'Female',
            NPI__c               = '0000000001',
            Rating               = 'Good',
            Website              = 'www.provider.net',
            Active__c            = 'True'
        );
        insert provider;
        Account patient = new Account(
            RecordTypeId         = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Patient').getRecordTypeId(),
            Salutation__c        = 'Dr.',
            Name                 = 'Test Patient',
            DateOfBirth__c       = Date.today().addYears(-30),
            Gender__c            = 'Male',
            Active__c            = 'True',
            Website              = 'www.patient.com',
            MemberPlan__c        = memberPlan.Id,
            Provider__c          = provider.Id
        );
        insert patient;
    }

    @isTest
    private static void test01_http_ok() {
        Account patient = [SELECT Id, Name, DateOfBirth__c, Gender__c, MemberPlan__c, Provider__c FROM Account WHERE RecordType.DeveloperName = 'Patient' LIMIT 1];
        Account provider = [SELECT Id, Name, NPI__c FROM Account WHERE RecordType.DeveloperName = 'Provider' LIMIT 1];
        MemberPlan__c memberPlan = [SELECT Id, Name, SubscriberId__c, GroupNumber__c, PolicyNumber__c FROM MemberPlan__c LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new InfinitusHttpResponseGenerator(200));
        Test.startTest();
        ServiceDetail__c serviceDetail = new ServiceDetail__c(
            MasterDetailToAccount__c  = patient.Id,
            ServiceDate__c            = Date.today(),
            Type__c                   = 'Consultation',
            DiagnosisCode__c          = 'E11.9',
            ProcedureCode__c          = '99213'
        );
        insert serviceDetail;
        Test.stopTest();
        List<CareBenefitVerifyRequest__c> cbvRequests = [SELECT Id, Name, Status__c, StatusReason__c FROM CareBenefitVerifyRequest__c];
        System.assertEquals(1, cbvRequests.size());
        System.assertEquals('Acknowledged', cbvRequests[0].Status__c);
        System.assertEquals(1, [SELECT COUNT() FROM CareBenefitVerification__c WHERE CareBenefitVerificationRequest__c = :cbvRequests[0].Id]);
    }

    @isTest
    private static void test02_http_error() {
        Account patient = [SELECT Id, Name, DateOfBirth__c, Gender__c, MemberPlan__c, Provider__c FROM Account WHERE RecordType.DeveloperName = 'Patient' LIMIT 1];
        Account provider = [SELECT Id, Name, NPI__c FROM Account WHERE RecordType.DeveloperName = 'Provider' LIMIT 1];
        MemberPlan__c memberPlan = [SELECT Id, Name, SubscriberId__c, GroupNumber__c, PolicyNumber__c FROM MemberPlan__c LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new InfinitusHttpResponseGenerator(999));
        Test.startTest();
        ServiceDetail__c serviceDetail = new ServiceDetail__c(
            MasterDetailToAccount__c  = patient.Id,
            ServiceDate__c            = Date.today(),
            Type__c                   = 'Consultation',
            DiagnosisCode__c          = 'E11.9',
            ProcedureCode__c          = '99213'
        );
        insert serviceDetail;
        Test.stopTest();
        List<CareBenefitVerifyRequest__c> cbvRequests = [SELECT Id, Name, Status__c, StatusReason__c FROM CareBenefitVerifyRequest__c];
        System.assertEquals(1, cbvRequests.size());
        System.assertEquals('999', cbvRequests[0].Status__c);
    }

    @isTest
    private static void test03_dml_exception() {
        Account patient = [SELECT Id, Name, DateOfBirth__c, Gender__c, MemberPlan__c, Provider__c FROM Account WHERE RecordType.DeveloperName = 'Patient' LIMIT 1];
        Account provider = [SELECT Id, Name, NPI__c FROM Account WHERE RecordType.DeveloperName = 'Provider' LIMIT 1];
        MemberPlan__c memberPlan = [SELECT Id, Name, SubscriberId__c, GroupNumber__c, PolicyNumber__c FROM MemberPlan__c LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new InfinitusHttpResponseGenerator(200));
        Test.startTest();
        ServiceDetail__c serviceDetail = new ServiceDetail__c(
            MasterDetailToAccount__c  = patient.Id,
            ServiceDate__c            = Date.today(),
            Type__c                   = 'Consultation',
            DiagnosisCode__c          = 'E11.9',
            ProcedureCode__c          = '99213'
        );
        insert serviceDetail;
        List<CareBenefitVerifyRequest__c> cbvRequests = [SELECT Id, Name, ServiceType__c, Status__c, StatusReason__c FROM CareBenefitVerifyRequest__c];
        cbvRequests[0].ServiceType__c = null;
        try {
            InfinitusAPIIntegration.updateCBVRecord(cbvRequests[0]);
        }
        catch(Exception e) {
            System.debug(LoggingLevel.ERROR, ('InfinitusAPIIntegrationTest.test03: ' + e.getMessage()));
        }
        Test.stopTest();
        System.assertEquals(1, cbvRequests.size());
        System.assertEquals('Not Submitted', cbvRequests[0].Status__c);
    }
}