force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Verified</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Decline to Say</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MemberPlan__c.field-meta.xml
<CustomField>
    <fullName>MemberPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Plan</label>
    <referenceTo>MemberPlan__c</referenceTo>
    <relationshipLabel>Plan Members</relationshipLabel>
    <relationshipName>MemberPlan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/NPI__c.field-meta.xml
<CustomField>
    <fullName>NPI__c</fullName>
    <label>National Provider Identifier (NPI)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeName__c</field>
            <operation>equals</operation>
            <value>Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ProviderSuffix__c.field-meta.xml
<CustomField>
    <fullName>ProviderSuffix__c</fullName>
    <label>Provider Suffix</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AE-C</fullName>
            </value>
            <value>
                <fullName>ANP</fullName>
            </value>
            <value>
                <fullName>ATC</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AuD</fullName>
            </value>
            <value>
                <fullName>CCC-A</fullName>
            </value>
            <value>
                <fullName>CCC-SLP</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>CCM</fullName>
            </value>
            <value>
                <fullName>CCRN</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CDA</fullName>
            </value>
            <value>
                <fullName>CDE</fullName>
            </value>
            <value>
                <fullName>CDTC</fullName>
            </value>
            <value>
                <fullName>CEN</fullName>
            </value>
            <value>
                <fullName>CFNP</fullName>
            </value>
            <value>
                <fullName>CGC</fullName>
            </value>
            <value>
                <fullName>ChD</fullName>
            </value>
            <value>
                <fullName>DCh</fullName>
            </value>
            <value>
                <fullName>CHN</fullName>
            </value>
            <value>
                <fullName>CHT</fullName>
            </value>
            <value>
                <fullName>CLE</fullName>
            </value>
            <value>
                <fullName>CLT</fullName>
            </value>
            <value>
                <fullName>CMA</fullName>
            </value>
            <value>
                <fullName>CNA</fullName>
            </value>
            <value>
                <fullName>CNM</fullName>
            </value>
            <value>
                <fullName>CNP</fullName>
            </value>
            <value>
                <fullName>CNS</fullName>
            </value>
            <value>
                <fullName>CNSC</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Patient.recordType-meta.xml
<RecordType>
    <fullName>Patient</fullName>
    <active>true</active>
    <description>Patient Details</description>
    <label>Patient</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <description>Provider Information</description>
    <label>Provider</label>
</RecordType>

force-app/main/default/objects/MemberPlan__c/MemberPlan__c.object-meta.xml
<CustomObject>
    <label>Member Plan</label>
    <nameField>
        <label>Insurance Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MemberPlan__c/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>Policy Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MemberPlan__c/fields/SubscriberId__c.field-meta.xml
<CustomField>
    <fullName>SubscriberId__c</fullName>
    <label>Subscriber Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountControllerTest.cls
@isTest
private class AccountControllerTest {
    @TestSetup
    public static void dataFactory() {
        MemberPlan__c memberPlan = new MemberPlan__c(
            Name                 = 'Test Member Plan',
            SubscriberId__c      = UUID.randomUUID().toString(),
            GroupNumber__c       = UUID.randomUUID().toString(),
            PolicyNumber__c      = UUID.randomUUID().toString()
        );
        insert memberPlan;
        Account provider = new Account(
            RecordTypeId         = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId(),
            Salutation__c        = 'Dr.',
            Name                 = 'Test Provider',
            ProviderSuffix__c    = 'MD',
            Gender__c            = 'Female',
            NPI__c               = '0000000001',
            Rating               = 'Good',
            Website              = 'www.provider.net',
            Active__c            = 'True'
        );
        insert provider;
        Account patient = new Account(
            RecordTypeId         = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Patient').getRecordTypeId(),
            Salutation__c        = 'Dr.',
            Name                 = 'Test Patient',
            DateOfBirth__c       = Date.today().addYears(-30),
            Gender__c            = 'Male',
            Active__c            = 'True',
            Website              = 'www.patient.com',
            MemberPlan__c        = memberPlan.Id,
            Provider__c          = provider.Id
        );
        insert patient;
        List<Contact> contacts = new List<Contact>();
        for (Integer i=0; i<10; i++) {
            Contact c = new Contact(
                FirstName = UUID.randomUUID().toString(),
                LastName  = ('0000' + String.valueOf(i + 1)).right(4),
                Phone     = '(000) 000-0000',
                AccountId = patient.Id
            );
            contacts.add(c);
        }
        insert contacts;
    }

    @isTest
    private static void test01_getAccounts() {
        Test.startTest();
        List<Account> accounts = AccountsController.getAccounts();
        Test.stopTest();
        System.assertNotEquals(0, accounts.size());
    }

    @isTest
    private static void test02_getContacts() {
        Account a = [SELECT Id, Name, Website FROM Account WHERE RecordType.DeveloperName  = 'Patient' LIMIT 1];
        Test.startTest();
        List<Contact> contacts = AccountsController.getContacts(a.Id);
        Test.stopTest();
        System.assertEquals(10, contacts.size());
    }
}