force-app/main/default/objects/CareBenefitVerifyRequest__c/CareBenefitVerifyRequest__c.object-meta.xml
<CustomObject>
    <label>Care Benefit Verification Request</label>
    <nameField>
        <displayFormat>CBVR-{0000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Benefit Verification Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest__c/fields/StatusReason__c.field-meta.xml
<CustomField>
    <fullName>StatusReason__c</fullName>
    <label>StatusReason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MyLwcController.cls
public with sharing class MyLwcController {
    @AuraEnabled(cacheable=true)
    public static String callout01() {
        String response = '';
        CareBenefitVerifyRequest__c cbvr = [SELECT Id, Name, Status__c, StatusReason__c FROM CareBenefitVerifyRequest__c LIMIT 1];
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:Infinitus/benefit-verification-request');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(System.JSON.serialize(cbvr));
        req.setTimeout(3000);
        HttpResponse res = new Http().send(req);
        if (res.getStatusCode() == 200) {
            response = res.getBody();
        }
        else {
            throw new AuraHandledException('HTTP ' + res.getStatusCode() + ': Callout failed.');
        }
        return response;
    }

    @AuraEnabled(cacheable=true)
    public static String callout02() {
        String response = '';
        CareBenefitVerifyRequest__c cbvr = [SELECT Id, Name, Status__c, StatusReason__c FROM CareBenefitVerifyRequest__c LIMIT 1];
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:Infinitus/benefit-verification-request');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(System.JSON.serialize(cbvr));
        req.setTimeout(3000);
        HttpResponse res = new Http().send(req);
        if (res.getStatusCode() == 200) {
            response = res.getBody();
        }
        else {
            throw new AuraHandledException('HTTP ' + res.getStatusCode() + ': Callout failed.');
        }
        return response;
    }

    @AuraEnabled(cacheable=true)
    public static String callout03() {
        String response = '';
        CareBenefitVerifyRequest__c cbvr = [SELECT Id, Name, Status__c, StatusReason__c FROM CareBenefitVerifyRequest__c LIMIT 1];
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:Infinitus/benefit-verification-request');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(System.JSON.serialize(cbvr));
        req.setTimeout(3000);
        HttpResponse res = new Http().send(req);
        if (res.getStatusCode() == 200) {
            response = res.getBody();
        }
        else {
            throw new AuraHandledException('HTTP ' + res.getStatusCode() + ': Callout failed.');
        }
        return response;
    }
}